import React, { createContext, useContext, useState, useCallback } from 'react';

export type Lang = 'en' | 'kn' | 'hi';

export interface Translations {
  [key: string]: string;
  // Navbar
  navHome: string; navTools: string; navAbout: string;
  navExperiments: string; navTutor: string; navDashboard: string;
  navLogin: string; navLogout: string; navProfile: string;
  // Home hero
  heroBadge: string; heroDesc: string;
  heroCta: string; heroCtaAi: string;
  // Home sections
  statsExperiments: string; statsSubjects: string; statsLabs: string; statsAi: string;
  subjectsHeading: string; subjectsSubheading: string; labsLabel: string;
  featuresHeading: string;
  feat1Title: string; feat1Desc: string;
  feat2Title: string; feat2Desc: string;
  feat3Title: string; feat3Desc: string;
  feat4Title: string; feat4Desc: string;
  feat5Title: string; feat5Desc: string;
  feat6Title: string; feat6Desc: string;
  ctaHeading: string; ctaSubheading: string; ctaBtn: string;
  // Tutor page
  tutorTitle: string; tutorSubtitle: string;
  tutorPlaceholder: string; tutorSend: string; tutorClear: string;
  tutorWelcome: string; tutorDisclaimer: string;
  tutorQ1: string; tutorQ2: string; tutorQ3: string;
  tutorQ4: string; tutorQ5: string; tutorQ6: string;
  // AI Floating
  aiGreeting: string; aiGreetingLab: string; aiGeneral: string;
  aiAskPlaceholder: string; aiAskLabPlaceholder: string;
  aiDisclaimer: string; aiError: string; aiRateLimit: string;
  // About page extras
  aboutOpenSource: string;
  aboutMissionTitle: string; aboutMissionP1: string; aboutMissionP2: string;
  aboutFeat1Title: string; aboutFeat1Desc: string;
  aboutFeat2Title: string; aboutFeat2Desc: string;
  aboutFeat3Title: string; aboutFeat3Desc: string;
  aboutFeat4Title: string; aboutFeat4Desc: string;
  aboutFeat5Title: string; aboutFeat5Desc: string;
  aboutFeat6Title: string; aboutFeat6Desc: string;
  aboutFeaturesSubheading: string;
  aboutSubjectsHeading: string; aboutSubjectsSubheading: string;
  aboutBuiltWith: string; aboutBuiltFor: string;
  aboutCtaSubheading: string;
  // Profile page extras
  profileEmailLabel: string; profileIdLabel: string; profileJoinedLabel: string;
  profileDisplayName: string; profileInstitution: string;
  profileGradeClass: string; profileBoardSyllabus: string;
  profileLanguageLabel: string; profileThemeColor: string;
  profileNotSet: string;
  // LabView tab labels & section headings
  tabAim: string; tabProcedure: string; tabInstructions: string; tabSimulation: string;
  tabObservation: string; tabResult: string; tabRealWorld: string; tabViva: string; tabQuiz: string;
  labAimHeading: string; labRequirements: string; labTheory: string; labObjectives: string;
  labSafetyPrecautions: string; labProcedureHeading: string; labInstructionsHeading: string;
  labVideoDemo: string; labVideoComingSoon: string; labSearchYouTube: string;
  labObservationTable: string; labResultConclusion: string; labExpectedResultFormat: string;
  labYourResult: string; labWriteResult: string; labExperimentalValue: string; labPercentageError: string;
  labRealWorldApps: string; labRealWorldDefault: string;
  labInteractiveViva: string; labRevealed: string; labShuffleQuestions: string;
  labRevealAnswer: string; labHowDidYouDo: string; labKnew: string; labUnsure: string; labMissed: string;
  labPracticeSummary: string; labSelfAssessmentQuiz: string; labAnswered: string; labExplanation: string;
  // Tools pages
  toolFormulaTitle: string; toolFormulaSubtitle: string; toolFormulaSearchPlaceholder: string; toolFormulaNoResults: string;
  toolSafetyTitle: string; toolSafetySubtitle: string; toolSafetySearchPlaceholder: string; toolSafetyNoResults: string;
  toolConstantsTitle: string; toolConstantsSubtitle: string; toolConstantsSearchPlaceholder: string; toolConstantsNoResults: string;
  toolCalculatorTitle: string; toolCalcStandard: string; toolCalcScientific: string;
  toolBioDiagramsTitle: string; toolBioDiagramsSubtitle: string;
  toolLogicGatesTitle: string; toolLogicGatesSubtitle: string;
  toolPeriodicTableTitle: string; toolPeriodicTableSubtitle: string;
  toolSearchAll: string; toolCopied: string;
  // Subjects list page
  subjectsTitle: string; subjectsDesc: string;
  subjectsExperiments: string; subjectsMore: string; subjectsExplore: string;
  // SubjectView (experiment list) page
  subjectNotFound: string; subjectBack: string; subjectKarnatakaPuc: string;
  subjectDifficulty: string; subjectStandard: string; subjectAll: string;
  subjectOpenLab: string; subjectNoExperiments: string;
  // Difficulty badge labels
  diffEasy: string; diffMedium: string; diffHard: string;
  // Standard filter
  std1stPuc: string; std2ndPuc: string;
  // Translated subject names
  namePhysics: string; nameChemistry: string; nameBiology: string; nameMath: string; nameCS: string;
  // Translated subject descriptions
  descPhysics: string; descChemistry: string; descBiology: string; descMath: string; descCS: string;
  // Tools hub page
  toolsTitle: string; toolsDesc: string;
  toolsFormulaSheet: string; toolsLogicGates: string; toolsPeriodicTable: string;
  toolsConstants: string; toolsCalculator: string; toolsSafetyGuide: string; toolsBioDiagrams: string;
}

const T: Record<Lang, Translations> = {
  en: {
    navHome: 'Home', navTools: 'Tools', navAbout: 'About',
    navExperiments: 'Experiments', navTutor: 'AI Tutor', navDashboard: 'Dashboard',
    navLogin: 'Log In', navLogout: 'Log Out', navProfile: 'Profile',
    heroBadge: 'Karnataka PUC Virtual Science Lab',
    heroDesc: '42 interactive virtual science experiments for Karnataka PUC students. Powered by AI, built with Canvas & SVG — learn by doing, digitally.',
    heroCta: 'Explore Labs →', heroCtaAi: 'AI Tutor',
    statsExperiments: 'Experiments', statsSubjects: 'Subjects', statsLabs: 'Karnataka PUC Labs', statsAi: 'AI Powered',
    subjectsHeading: '5 Subjects, 42 Labs',
    subjectsSubheading: 'Every experiment aligned with the Karnataka Pre-University Course curriculum.',
    labsLabel: 'Labs',
    featuresHeading: 'Why E-Prayog?',
    feat1Title: 'Interactive 2D Simulations', feat1Desc: 'Rich Canvas & SVG labs for every experiment — no 3D required.',
    feat2Title: 'AI Lab Tutor', feat2Desc: 'Context-aware Gemini AI that knows your current experiment.',
    feat3Title: 'Karnataka PUC Syllabus', feat3Desc: 'Every lab aligned with 1st and 2nd PUC curriculum.',
    feat4Title: 'Real-time Calculations', feat4Desc: 'Live physics engine with error analysis and graphing.',
    feat5Title: 'Mobile Responsive', feat5Desc: 'Learn on any device — phone, tablet, or laptop.',
    feat6Title: 'Viva Questions', feat6Desc: 'Prepare for practical exams with curated viva Q&A.',
    ctaHeading: 'Ready to experiment?', ctaSubheading: 'Start your virtual lab journey — no chemicals, no equipment, just learning.', ctaBtn: 'Start Learning →',
    tutorTitle: 'AI Lab Tutor', tutorSubtitle: 'Powered by Gemini AI • Karnataka PUC Syllabus',
    tutorPlaceholder: 'Ask anything about Karnataka PUC Science...', tutorSend: 'Send', tutorClear: 'Clear chat',
    tutorWelcome: 'Namaskara. I am your E-Prayog AI Tutor. Ask me anything about your Karnataka PUC Science practicals — Physics, Chemistry, Biology, Math, or Computer Science.',
    tutorDisclaimer: 'Powered by Gemini AI — always verify important information',
    tutorQ1: "What is Ohm's Law?", tutorQ2: 'Explain photosynthesis', tutorQ3: 'What is the mirror formula?',
    tutorQ4: 'Difference between mitosis and meiosis', tutorQ5: 'What is Wheatstone bridge?', tutorQ6: 'Explain acid-base titration',
    aiGreeting: "Namaskara. I'm your E-Prayog AI Tutor. Ask me about any Karnataka PUC experiment.",
    aiGreetingLab: "Namaskara. I see you're working on **{lab}** ({subject}). Ask me anything about this experiment.",
    aiGeneral: 'Gemini AI • General mode',
    aiAskPlaceholder: 'Ask about any experiment…', aiAskLabPlaceholder: 'Ask about {lab}…',
    aiDisclaimer: 'Powered by Gemini AI — verify important info',
    aiError: 'Connection issue. Please try again.', aiRateLimit: 'Rate limit exceeded. Please wait a minute.',
    aboutTitle: 'Redefining Science Education in Karnataka',
    aboutDesc: 'E-Prayog brings every PUC experiment to life through interactive 2D simulations, AI tutoring, and a curriculum built specifically for Karnataka students.',
    aboutExploreLabs: 'Explore Labs',
    aboutTryTutor: 'Try AI Tutor',
    toolsTitle: 'Scientific Tools',
    toolsDesc: 'Quick access to references, calculators, and interactive study aids for all your science experiments.',
    toolsFormulaSheet: 'Formula Sheet',
    toolsLogicGates: 'Logic Gates',
    toolsPeriodicTable: 'Periodic Table',
    toolsConstants: 'Constants',
    toolsCalculator: 'Calculator',
    toolsSafetyGuide: 'Safety Guide',
    toolsBioDiagrams: 'Bio Diagrams',
    subjectsTitle: 'Virtual Laboratories',
    subjectsDesc: 'Choose a subject to explore interactive experiments aligned with the Karnataka PUC syllabus.',
    subjectsExperiments: 'Experiments',
    subjectsMore: 'more',
    subjectsExplore: 'Explore',
    subjectBack: 'Back to Subjects',
    subjectNotFound: 'Subject not found.',
    subjectKarnatakaPuc: 'Karnataka PUC',
    subjectDifficulty: 'Difficulty',
    subjectStandard: 'Standard',
    subjectAll: 'All',
    subjectOpenLab: 'Open Lab',
    subjectNoExperiments: 'No experiments match the selected filters.',
    diffEasy: 'Easy', diffMedium: 'Medium', diffHard: 'Hard',
    std1stPuc: '1st PUC', std2ndPuc: '2nd PUC',
    namePhysics: 'Physics', nameChemistry: 'Chemistry', nameBiology: 'Biology', nameMath: 'Math', nameCS: 'CS',
    descPhysics: 'Explore mechanics, optics, electricity & magnetism through interactive 2D simulations aligned with Karnataka PUC syllabus.',
    descChemistry: 'Perform titrations, salt analysis, chromatography, and reaction kinetics through vivid 2D simulations for Karnataka PUC.',
    descBiology: 'Explore cell biology, genetics, plant physiology, and biochemistry through vivid 2D simulations for Karnataka PUC.',
    descMath: 'Visualise trigonometry, algebra, statistics, and probability concepts with interactive 2D explorations for Karnataka PUC.',
    descCS: 'Visualise sorting algorithms, data structures, and logic gates through animated 2D simulations for Karnataka PUC.',
    contactTitle: 'Send Us Feedback',
    contactDesc: 'Help us improve E-Prayog. Your feedback matters!',
    contactThankYou: 'Thank You!',
    contactSubmitted: 'Your feedback has been submitted successfully.',
    contactSubmitAnother: 'Submit Another',
    contactRatingPrompt: 'How would you rate E-Prayog?',
    contactCategory: 'Category',
    contactMessage: 'Your Message',
    contactPlaceholder: 'Tell us what you think... (minimum 20 characters)',
    contactSubmit: 'Submit Feedback',
    contactRatingRequired: 'Please select a rating.',
    contactMessageMin: 'Message must be at least 20 characters.',
    contactFailed: 'Failed to submit. Please try again.',
    footerDesc: 'Empowering Karnataka PUC students with immersive virtual science simulations and AI-driven mentorship. Learn by doing — digitally.',
    footerPlatform: 'Platform',
    footerVirtualLabs: 'Virtual Labs',
    footerSupport: 'Support',
    footerContactUs: 'Contact Us',
    footerAboutUs: 'About Us',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms & Conditions',
    footerFeedback: 'Feedback',
    footerFeedbackDesc: 'Help us improve your learning experience.',
    footerFeedbackPlaceholder: 'Your suggestions...',
    footerFeedbackThanks: 'Thank you for your feedback!',
    footerRights: 'All rights reserved.',
    footerBuiltFor: 'Built for',
    footerKarnatakaStudents: 'Karnataka PUC Students',
    loginWelcome: 'Welcome Back',
    loginCreateAccount: 'Create Account',
    loginCompleteProfile: 'Complete Your Profile',
    loginJoinToday: 'Join E-Prayog today',
    loginFewDetails: 'Just a few more details',
    loginToAccount: 'Log in to your E-Prayog account',
    loginTeacherBadge: 'Teacher Login',
    loginAdminBadge: 'Admin Login',
    loginBack: 'Back',
    loginFullName: 'Full Name',
    loginPassword: 'Password',
    loginNext: 'Next',
    loginOr: 'OR',
    loginContinueGoogle: 'Continue with Google',
    loginHaveAccount: 'Already have an account?',
    loginNoAccount: "Don't have an account?",
    loginSignUp: 'Sign Up',
    loginTeacherHint: 'Teacher accounts are created by the Admin.',
    loginAdminHint: 'Admin credentials are set during platform setup.',
    profileTitle: 'Your Profile',
    profileSaved: 'Profile Saved!',
    profileEdit: 'Edit Profile',
    profileAccountSettings: 'Account Settings',
    profileCancel: 'Cancel',
    profileSave: 'Save',
    profileStats: 'Your Stats',
    profileCurrentStreak: 'Current Streak',
    profileLabsCompleted: 'Labs Completed',
    profileOverallProgress: 'Overall Progress',
    profileYourTeacher: 'Your Teacher',
    profileJoinClassHelp: "Enter your teacher's 6-character class code.",
    profileLeave: 'Leave',
    profileLinked: 'Linked!',
    profileSubjectProgress: 'Subject Progress',
    labExperimentNotFound: 'Experiment not found.',
    labBackTo: 'Back to',
    labPrintObservation: 'Print Observation',
    labNoObservation: 'No observation table defined for this experiment.',
    labNoViva: 'Viva questions for this experiment will be added soon.',
    labNoQuiz: 'Quiz questions for this experiment will be added soon.',
    labQuizCompleted: 'Quiz Completed!',
    labSubmitQuiz: 'Submit Quiz',
    labRetakeQuiz: 'Retake Quiz',
    labPrevious: 'Previous',
    labFinish: 'Finish',
    aboutOpenSource: 'Open Source Science Lab',
    aboutMissionTitle: 'Our Mission',
    aboutMissionP1: 'E-Prayog aims to democratize practical science education for Karnataka PUC students. We believe every student — regardless of whether their school has a physical lab — deserves hands-on experimental learning.',
    aboutMissionP2: 'Our 2D interactive simulations recreate real experiments faithfully, complete with observations, viva voce, quizzes, and AI-powered doubt solving. All running entirely in the browser — free, forever.',
    aboutFeat1Title: '2D Interactive Simulations', aboutFeat1Desc: 'All experiments run in the browser — no WebGL, no downloads.',
    aboutFeat2Title: 'AI Science Tutor', aboutFeat2Desc: 'Ask doubts in English, Kannada, or Hindi — powered by Gemini.',
    aboutFeat3Title: 'Karnataka PUC Aligned', aboutFeat3Desc: 'Covers both 1st and 2nd PUC syllabus for all 5 science subjects.',
    aboutFeat4Title: 'Safe & Accessible', aboutFeat4Desc: 'No chemicals, no risk — experiment anytime, anywhere.',
    aboutFeat5Title: 'Multilingual Support', aboutFeat5Desc: 'Full English, Kannada, and Hindi support throughout.',
    aboutFeat6Title: 'Gamified Learning', aboutFeat6Desc: 'Quizzes, viva voce, assignments, and completion tracking.',
    aboutFeaturesSubheading: 'Everything you need for practical science education, built for the Indian classroom.',
    aboutSubjectsHeading: 'Subjects Covered', aboutSubjectsSubheading: 'Comprehensive coverage across all 5 PUC science streams.',
    aboutBuiltWith: 'Built with', aboutBuiltFor: 'for Karnataka Students',
    aboutCtaSubheading: 'Join thousands of Karnataka students already learning through interactive simulations.',
    profileEmailLabel: 'Email', profileIdLabel: 'ID', profileJoinedLabel: 'Joined',
    profileDisplayName: 'Display Name', profileInstitution: 'Institution',
    profileGradeClass: 'Grade / Class', profileBoardSyllabus: 'Board / Syllabus',
    profileLanguageLabel: 'Language', profileThemeColor: 'Theme Color',
    profileNotSet: 'Not set',
    tabAim: 'Aim & Theory', tabProcedure: 'Procedure', tabInstructions: 'Instructions & Video', tabSimulation: 'Simulation',
    tabObservation: 'Observation', tabResult: 'Result', tabRealWorld: 'Real World', tabViva: 'Viva Questions', tabQuiz: 'Quiz',
    labAimHeading: 'Aim', labRequirements: 'Requirements', labTheory: 'Theory', labObjectives: 'Objectives',
    labSafetyPrecautions: 'Safety Precautions', labProcedureHeading: 'Procedure', labInstructionsHeading: 'Lab Instructions',
    labVideoDemo: 'Video Demonstration', labVideoComingSoon: 'Video demonstration coming soon', labSearchYouTube: 'Search on YouTube',
    labObservationTable: 'Observation Table', labResultConclusion: 'Result & Conclusion', labExpectedResultFormat: 'Expected result format:',
    labYourResult: 'Your Result', labWriteResult: 'Write your result and conclusion here...', labExperimentalValue: 'Experimental Value', labPercentageError: 'Percentage Error',
    labRealWorldApps: 'Real-World Applications', labRealWorldDefault: 'Real-world applications for this experiment include:',
    labInteractiveViva: 'Interactive Viva Voce', labRevealed: 'revealed', labShuffleQuestions: 'Shuffle Questions',
    labRevealAnswer: 'Reveal Answer', labHowDidYouDo: 'How did you do?', labKnew: 'Knew', labUnsure: 'Unsure', labMissed: 'Missed',
    labPracticeSummary: 'Practice Summary', labSelfAssessmentQuiz: 'Self-Assessment Quiz', labAnswered: 'answered', labExplanation: 'Explanation:',
    toolFormulaTitle: 'Formula Sheet', toolFormulaSubtitle: 'Standard formulas and equations for quick reference.',
    toolFormulaSearchPlaceholder: 'Search formulas...', toolFormulaNoResults: 'No formulas matched your search.',
    toolSafetyTitle: 'Laboratory Safety Guide', toolSafetySubtitle: 'Essential safety protocols and emergency procedures for all laboratory experiments.',
    toolSafetySearchPlaceholder: 'Search guidelines...', toolSafetyNoResults: 'No safety rules matched your search.',
    toolConstantsTitle: 'Physical Constants', toolConstantsSubtitle: 'Reference values for universal and fundamental physical constants.',
    toolConstantsSearchPlaceholder: 'Search constants...', toolConstantsNoResults: 'No constants matched your search.',
    toolCalculatorTitle: 'Calculator', toolCalcStandard: 'Standard', toolCalcScientific: 'Scientific',
    toolBioDiagramsTitle: 'Biology Diagrams', toolBioDiagramsSubtitle: 'Interactive labelled diagrams for Biology.',
    toolLogicGatesTitle: 'Logic Gates Simulator', toolLogicGatesSubtitle: 'Explore boolean logic with interactive gate simulations.',
    toolPeriodicTableTitle: 'Periodic Table', toolPeriodicTableSubtitle: 'Interactive periodic table of elements.',
    toolSearchAll: 'All', toolCopied: 'Copied!'
  },

  kn: {
    navHome: 'ಮುಖಪುಟ', navTools: 'ಪರಿಕರಗಳು', navAbout: 'ಬಗ್ಗೆ',
    navExperiments: 'ಪ್ರಯೋಗಗಳು', navTutor: 'AI ಶಿಕ್ಷಕ', navDashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    navLogin: 'ಲಾಗಿನ್', navLogout: 'ಲಾಗ್ ಔಟ್', navProfile: 'ಪ್ರೊಫೈಲ್',
    heroBadge: 'ಕರ್ನಾಟಕ PUC ವರ್ಚುವಲ್ ವಿಜ್ಞಾನ ಪ್ರಯೋಗಾಲಯ',
    heroDesc: 'ಕರ್ನಾಟಕ PUC ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ 42 ಸಂವಾದಾತ್ಮಕ ವರ್ಚುವಲ್ ವಿಜ್ಞಾನ ಪ್ರಯೋಗಗಳು. AI ಮತ್ತು Canvas & SVG ನಿಂದ ನಿರ್ಮಿಸಲಾಗಿದೆ — ಡಿಜಿಟಲ್ ರೀತಿಯಲ್ಲಿ ಕಲಿಯಿರಿ.',
    heroCta: 'ಪ್ರಯೋಗಾಲಯ ನೋಡಿ →', heroCtaAi: 'AI ಶಿಕ್ಷಕ',
    statsExperiments: 'ಪ್ರಯೋಗಗಳು', statsSubjects: 'ವಿಷಯಗಳು', statsLabs: 'ಕರ್ನಾಟಕ PUC ಲ್ಯಾಬ್ಸ್', statsAi: 'AI ಚಾಲಿತ',
    subjectsHeading: '5 ವಿಷಯಗಳು, 42 ಪ್ರಯೋಗಗಳು',
    subjectsSubheading: 'ಕರ್ನಾಟಕ ಪದವಿಪೂರ್ವ ಪಠ್ಯಕ್ರಮಕ್ಕೆ ಹೊಂದಿಕೊಂಡ ಪ್ರತಿ ಪ್ರಯೋಗ.',
    labsLabel: 'ಪ್ರಯೋಗಗಳು',
    featuresHeading: 'ಇ-ಪ್ರಯೋಗ ಏಕೆ?',
    feat1Title: 'ಸಂವಾದಾತ್ಮಕ 2D ಸಿಮ್ಯುಲೇಷನ್', feat1Desc: 'ಪ್ರತಿ ಪ್ರಯೋಗಕ್ಕೂ ಸಮೃದ್ಧ Canvas & SVG ಲ್ಯಾಬ್‌ಗಳು.',
    feat2Title: 'AI ಪ್ರಯೋಗಾಲಯ ಶಿಕ್ಷಕ', feat2Desc: 'ನಿಮ್ಮ ಪ್ರಯೋಗ ತಿಳಿದ Gemini AI ಸಹಾಯಕ.',
    feat3Title: 'ಕರ್ನಾಟಕ PUC ಪಠ್ಯಕ್ರಮ', feat3Desc: '1ನೇ ಮತ್ತು 2ನೇ PUC ಪಠ್ಯಕ್ರಮಕ್ಕೆ ಹೊಂದಿಕೊಂಡ ಪ್ರಯೋಗಗಳು.',
    feat4Title: 'ರಿಯಲ್-ಟೈಮ್ ಲೆಕ್ಕಾಚಾರ', feat4Desc: 'ದೋಷ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಗ್ರಾಫಿಂಗ್ ಸಹಿತ ಭೌತಶಾಸ್ತ್ರ ಎಂಜಿನ್.',
    feat5Title: 'ಮೊಬೈಲ್ ಸ್ನೇಹಿ', feat5Desc: 'ಯಾವುದೇ ಸಾಧನದಲ್ಲಿ ಕಲಿಯಿರಿ — ಫೋನ್, ಟ್ಯಾಬ್ಲೆಟ್ ಅಥವಾ ಲ್ಯಾಪ್‌ಟಾಪ್.',
    feat6Title: 'ವಿವಾ ಪ್ರಶ್ನೆಗಳು', feat6Desc: 'ಆಯ್ದ ವಿವಾ Q&A ನೊಂದಿಗೆ ಪ್ರಾಯೋಗಿಕ ಪರೀಕ್ಷೆಗೆ ಸಿದ್ಧರಾಗಿ.',
    ctaHeading: 'ಪ್ರಯೋಗ ಮಾಡಲು ಸಿದ್ಧರಾ?', ctaSubheading: 'ವರ್ಚುವಲ್ ಲ್ಯಾಬ್ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ — ರಾಸಾಯನಿಕ ಇಲ್ಲ, ಉಪಕರಣ ಇಲ್ಲ, ಕೇವಲ ಕಲಿಕೆ.', ctaBtn: 'ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ →',
    tutorTitle: 'AI ಪ್ರಯೋಗಾಲಯ ಶಿಕ್ಷಕ', tutorSubtitle: 'Gemini AI ಚಾಲಿತ • ಕರ್ನಾಟಕ PUC ಪಠ್ಯಕ್ರಮ',
    tutorPlaceholder: 'ಕರ್ನಾಟಕ PUC ವಿಜ್ಞಾನದ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ...', tutorSend: 'ಕಳುಹಿಸಿ', tutorClear: 'ಚಾಟ್ ಅಳಿಸಿ',
    tutorWelcome: 'ನಮಸ್ಕಾರ. ನಾನು ನಿಮ್ಮ ಇ-ಪ್ರಯೋಗ AI ಶಿಕ್ಷಕ. ಕರ್ನಾಟಕ PUC ವಿಜ್ಞಾನ ಪ್ರಾಯೋಗಿಕ — ಭೌತಶಾಸ್ತ್ರ, ರಸಾಯನಶಾಸ್ತ್ರ, ಜೀವಶಾಸ್ತ್ರ, ಗಣಿತ ಅಥವಾ ಕಂಪ್ಯೂಟರ್ ವಿಜ್ಞಾನ — ಏನಾದರೂ ಕೇಳಿ.',
    tutorDisclaimer: 'Gemini AI ಚಾಲಿತ — ಮಹತ್ವದ ಮಾಹಿತಿಯನ್ನು ಯಾವಾಗಲೂ ಪರಿಶೀಲಿಸಿ',
    tutorQ1: "ಓಮ್ ನಿಯಮ ಏನು?", tutorQ2: 'ದ್ಯುತಿಸಂಶ್ಲೇಷಣೆ ವಿವರಿಸಿ', tutorQ3: 'ದರ್ಪಣ ಸೂತ್ರ ಏನು?',
    tutorQ4: 'ಮೈಟೋಸಿಸ್ ಮತ್ತು ಮಿಯೋಸಿಸ್ ವ್ಯತ್ಯಾಸ', tutorQ5: 'ವೀಟ್‌ಸ್ಟೋನ್ ಬ್ರಿಜ್ ತತ್ತ್ವ', tutorQ6: 'ಆಮ್ಲ-ಕ್ಷಾರ ಅನುಮಾಪನ ವಿವರಿಸಿ',
    aiGreeting: "ನಮಸ್ಕಾರ. ನಾನು ನಿಮ್ಮ ಇ-ಪ್ರಯೋಗ AI ಶಿಕ್ಷಕ. ಯಾವುದೇ ಕರ್ನಾಟಕ PUC ಪ್ರಯೋಗದ ಬಗ್ಗೆ ಕೇಳಿ.",
    aiGreetingLab: "ನಮಸ್ಕಾರ. ನೀವು **{lab}** ({subject}) ಮೇಲೆ ಕೆಲಸ ಮಾಡುತ್ತಿರುವಿರಿ. ಈ ಪ್ರಯೋಗದ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ.",
    aiGeneral: 'Gemini AI • ಸಾಮಾನ್ಯ ಮೋಡ್',
    aiAskPlaceholder: 'ಯಾವುದೇ ಪ್ರಯೋಗದ ಬಗ್ಗೆ ಕೇಳಿ…', aiAskLabPlaceholder: '{lab} ಬಗ್ಗೆ ಕೇಳಿ…',
    aiDisclaimer: 'Gemini AI ಚಾಲಿತ — ಮಾಹಿತಿ ಪರಿಶೀಲಿಸಿ',
    aiError: 'ಸಂಪರ್ಕ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', aiRateLimit: 'ದರ ಮಿತಿ ಮೀರಿದೆ. ದಯವಿಟ್ಟು ಒಂದು ನಿಮಿಷ ಕಾಯಿರಿ.',
    aboutTitle: 'ಕರ್ನಾಟಕದಲ್ಲಿ ವಿಜ್ಞಾನ ಶಿಕ್ಷಣವನ್ನು ಮರುಪರಿಭಾಷಿಸುವುದು',
    aboutDesc: 'ಇ-ಪ್ರಯೋಗ ಸಂವಾದಾತ್ಮಕ 2D ಸಿಮ್ಯುಲೇಷನ್, AI ಶಿಕ್ಷಕ ಮತ್ತು ಕರ್ನಾಟಕ ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಹೊಂದಿಸಿದ ಪಠ್ಯಕ್ರಮದ ಮೂಲಕ ಪ್ರತಿ PUC ಪ್ರಯೋಗವನ್ನು ಜೀವಂತಗೊಳಿಸುತ್ತದೆ.',
    aboutExploreLabs: 'ಪ್ರಯೋಗಾಲಯ ನೋಡಿ',
    aboutTryTutor: 'AI ಶಿಕ್ಷಕ ಪ್ರಯತ್ನಿಸಿ',
    toolsTitle: 'ವೈಜ್ಞಾನಿಕ ಪರಿಕರಗಳು',
    toolsDesc: 'ನಿಮ್ಮ ವಿಜ್ಞಾನ ಪ್ರಯೋಗಗಳಿಗೆ ಉಲ್ಲೇಖಗಳು, ಕ್ಯಾಲ್ಕುಲೇಟರ್‌ಗಳು ಮತ್ತು ಸಂವಾದಾತ್ಮಕ ಅಧ್ಯಯನ ಸಹಾಯಕಗಳಿಗೆ ತ್ವರಿತ ಪ್ರವೇಶ.',
    toolsFormulaSheet: 'ಸೂತ್ರಪತ್ರ',
    toolsLogicGates: 'ಲಾಜಿಕ್ ಗೇಟ್‌ಗಳು',
    toolsPeriodicTable: 'ಆವರ್ತನ ಪಟ್ಟಿಕೆ',
    toolsConstants: 'ಸ್ಥಿರಾಂಕಗಳು',
    toolsCalculator: 'ಕ್ಯಾಲ್ಕುಲೇಟರ್',
    toolsSafetyGuide: 'ಸುರಕ್ಷತಾ ಮಾರ್ಗದರ್ಶಿ',
    toolsBioDiagrams: 'ಜೀವಶಾಸ್ತ್ರ ಚಿತ್ರಣಗಳು',
    subjectsTitle: 'ವರ್ಚುವಲ್ ಪ್ರಯೋಗಾಲಯಗಳು',
    subjectsDesc: 'ಕರ್ನಾಟಕ PUC ಪಠ್ಯಕ್ರಮಕ್ಕೆ ಹೊಂದುವ ಸಂವಾದಾತ್ಮಕ ಪ್ರಯೋಗಗಳನ್ನು ನೋಡಲು ವಿಷಯ ಆಯ್ಕೆಮಾಡಿ.',
    subjectsExperiments: 'ಪ್ರಯೋಗಗಳು',
    subjectsMore: 'ಇನ್ನಷ್ಟು',
    subjectsExplore: 'ಅನ್ವೇಷಿಸಿ',
    subjectBack: 'ವಿಷಯಗಳಿಗೆ ಹಿಂದಿರುಗಿ',
    subjectNotFound: 'ವಿಷಯ ಕಂಡುಬಂದಿಲ್ಲ.',
    subjectKarnatakaPuc: 'ಕರ್ನಾಟಕ PUC',
    subjectDifficulty: 'ಕಷ್ಟತೆ',
    subjectStandard: 'ತರಗತಿ',
    subjectAll: 'ಎಲ್ಲಾ',
    subjectOpenLab: 'ಲ್ಯಾಬ್ ತೆರೆಯಿರಿ',
    subjectNoExperiments: 'ಆಯ್ಕೆ ಮಾಡಿದ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಪ್ರಯೋಗಗಳು ದೊರಕಲಿಲ್ಲ.',
    diffEasy: 'ಸುಲಭ', diffMedium: 'ಮಧ್ಯಮ', diffHard: 'ಕಷ್ಟ',
    std1stPuc: '1ನೇ PUC', std2ndPuc: '2ನೇ PUC',
    namePhysics: 'ಭೌತಶಾಸ್ತ್ರ', nameChemistry: 'ರಸಾಯನಶಾಸ್ತ್ರ', nameBiology: 'ಜೀವಶಾಸ್ತ್ರ', nameMath: 'ಗಣಿತ', nameCS: 'ಕಂಪ್ಯೂಟರ್ ವಿಜ್ಞಾನ',
    descPhysics: 'ಕರ್ನಾಟಕ PUC ಪಠ್ಯಕ್ರಮಕ್ಕೆ ಹೊಂದಿಕೊಂಡ ಸಂವಾದಾತ್ಮಕ 2D ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ಯಂತ್ರಶಾಸ್ತ್ರ, ದ್ಯುತಿಶಾಸ್ತ್ರ, ವಿದ್ಯುಚ್ಛಕ್ತಿ ಮತ್ತು ಕಾಂತವಿದ್ಯೆ ಅನ್ವೇಷಿಸಿ.',
    descChemistry: 'ಕರ್ನಾಟಕ PUC ಗಾಗಿ ಅನುಮಾಪನ, ಲವಣ ವಿಶ್ಲೇಷಣೆ, ವರ್ಣ ಲೇಪನ ಮತ್ತು ಕ್ರಿಯಾ ಚಲನಶಾಸ್ತ್ರ ಸಂವಾದಾತ್ಮಕ 2D ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ನಿರ್ವಹಿಸಿ.',
    descBiology: 'ಕರ್ನಾಟಕ PUC ಗಾಗಿ ಕೋಶ ಜೀವಶಾಸ್ತ್ರ, ಆನುವಂಶಿಕತೆ, ಸಸ್ಯ ಶರೀರ ಕ್ರಿಯಾಶಾಸ್ತ್ರ ಮತ್ತು ಜೀವರಸಾಯನಶಾಸ್ತ್ರ 2D ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ಅನ್ವೇಷಿಸಿ.',
    descMath: 'ಕರ್ನಾಟಕ PUC ಗಾಗಿ ತ್ರಿಕೋಣಮಿತಿ, ಬೀಜಗಣಿತ, ಸಾಂಖ್ಯಿಕ ಮತ್ತು ಸಂಭಾವ್ಯತೆ ಪರಿಕಲ್ಪನೆಗಳನ್ನು ಸಂವಾದಾತ್ಮಕ 2D ಅನ್ವೇಷಣೆಗಳ ಮೂಲಕ ದೃಶ್ಯೀಕರಿಸಿ.',
    descCS: 'ಕರ್ನಾಟಕ PUC ಗಾಗಿ ವಿಂಗಡಣಾ ಅಲ್ಗಾರಿದಮ್‌ಗಳು, ಡೇಟಾ ರಚನೆಗಳು ಮತ್ತು ಲಾಜಿಕ್ ಗೇಟ್‌ಗಳನ್ನು ಅನಿಮೇಟೆಡ್ 2D ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ದೃಶ್ಯೀಕರಿಸಿ.',
    contactTitle: 'ನಮಗೆ ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ',
    contactDesc: 'ಇ-ಪ್ರಯೋಗವನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ. ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಅಮೂಲ್ಯ!',
    contactThankYou: 'ಧನ್ಯವಾದಗಳು!',
    contactSubmitted: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ.',
    contactSubmitAnother: 'ಮತ್ತೊಂದು ಸಲ್ಲಿಸಿ',
    contactRatingPrompt: 'ಇ-ಪ್ರಯೋಗಕ್ಕೆ ನೀವು ಎಷ್ಟು ರೇಟಿಂಗ್ ಕೊಡುತ್ತೀರಿ?',
    contactCategory: 'ವರ್ಗ',
    contactMessage: 'ನಿಮ್ಮ ಸಂದೇಶ',
    contactPlaceholder: 'ನಿಮ್ಮ ಅಭಿಪ್ರಾಯ ತಿಳಿಸಿ... (ಕನಿಷ್ಠ 20 ಅಕ್ಷರಗಳು)',
    contactSubmit: 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
    contactRatingRequired: 'ದಯವಿಟ್ಟು ರೇಟಿಂಗ್ ಆಯ್ಕೆಮಾಡಿ.',
    contactMessageMin: 'ಸಂದೇಶ ಕನಿಷ್ಠ 20 ಅಕ್ಷರಗಳಿರಬೇಕು.',
    contactFailed: 'ಸಲ್ಲಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    footerDesc: 'ಕರ್ನಾಟಕ PUC ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಸಂವೇದನಾತ್ಮಕ ವರ್ಚುವಲ್ ವಿಜ್ಞಾನ ಸಿಮ್ಯುಲೇಷನ್ ಮತ್ತು AI ಮಾರ್ಗದರ್ಶನ ಒದಗಿಸುತ್ತೇವೆ. ಮಾಡಿ ಕಲಿಯಿರಿ — ಡಿಜಿಟಲ್ ರೀತಿಯಲ್ಲಿ.',
    footerPlatform: 'ವೇದಿಕೆ',
    footerVirtualLabs: 'ವರ್ಚುವಲ್ ಲ್ಯಾಬ್ಸ್',
    footerSupport: 'ಬೆಂಬಲ',
    footerContactUs: 'ಸಂಪರ್ಕಿಸಿ',
    footerAboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    footerPrivacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    footerTerms: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    footerFeedback: 'ಪ್ರತಿಕ್ರಿಯೆ',
    footerFeedbackDesc: 'ನಿಮ್ಮ ಕಲಿಕೆಯ ಅನುಭವ ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ.',
    footerFeedbackPlaceholder: 'ನಿಮ್ಮ ಸಲಹೆಗಳು...',
    footerFeedbackThanks: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!',
    footerRights: 'ಎಲ್ಲ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    footerBuiltFor: 'ಇದಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ',
    footerKarnatakaStudents: 'ಕರ್ನಾಟಕ PUC ವಿದ್ಯಾರ್ಥಿಗಳು',
    loginWelcome: 'ಮತ್ತೆ ಸ್ವಾಗತ',
    loginCreateAccount: 'ಖಾತೆ ರಚಿಸಿ',
    loginCompleteProfile: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    loginJoinToday: 'ಇಂದು ಇ-ಪ್ರಯೋಗಕ್ಕೆ ಸೇರಿ',
    loginFewDetails: 'ಇನ್ನಷ್ಟು ಕೆಲವು ವಿವರಗಳು',
    loginToAccount: 'ನಿಮ್ಮ ಇ-ಪ್ರಯೋಗ ಖಾತೆಗೆ ಲಾಗಿನ್ ಆಗಿ',
    loginTeacherBadge: 'ಶಿಕ್ಷಕರ ಲಾಗಿನ್',
    loginAdminBadge: 'ನಿರ್ವಾಹಕ ಲಾಗಿನ್',
    loginBack: 'ಹಿಂದೆ',
    loginFullName: 'ಪೂರ್ಣ ಹೆಸರು',
    loginPassword: 'ಪಾಸ್‌ವರ್ಡ್',
    loginNext: 'ಮುಂದೆ',
    loginOr: 'ಅಥವಾ',
    loginContinueGoogle: 'Google ಮೂಲಕ ಮುಂದುವರಿಸಿ',
    loginHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೆ?',
    loginNoAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    loginSignUp: 'ಸೈನ್ ಅಪ್',
    loginTeacherHint: 'ಶಿಕ್ಷಕರ ಖಾತೆಗಳನ್ನು ನಿರ್ವಾಹಕರು ರಚಿಸುತ್ತಾರೆ.',
    loginAdminHint: 'ನಿರ್ವಾಹಕ ವಿವರಗಳನ್ನು ವೇದಿಕೆ ಸ್ಥಾಪನೆಯಾಗುವಾಗ ಹೊಂದಿಸಲಾಗುತ್ತದೆ.',
    profileTitle: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್',
    profileSaved: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ!',
    profileEdit: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    profileAccountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    profileCancel: 'ರದ್ದುಮಾಡಿ',
    profileSave: 'ಉಳಿಸಿ',
    profileStats: 'ನಿಮ್ಮ ಅಂಕಿಅಂಶಗಳು',
    profileCurrentStreak: 'ಪ್ರಸ್ತುತ ಸ್ಟ್ರೀಕ್',
    profileLabsCompleted: 'ಪೂರ್ಣಗೊಂಡ ಲ್ಯಾಬ್‌ಗಳು',
    profileOverallProgress: 'ಒಟ್ಟಾರೆ ಪ್ರಗತಿ',
    profileYourTeacher: 'ನಿಮ್ಮ ಶಿಕ್ಷಕ',
    profileJoinClassHelp: 'ನಿಮ್ಮ ಶಿಕ್ಷಕರ 6 ಅಕ್ಷರದ ವರ್ಗ ಕೋಡ್ ನಮೂದಿಸಿ.',
    profileLeave: 'ಬಿಟ್ಟುಬಿಡಿ',
    profileLinked: 'ಲಿಂಕ್ ಆಗಿದೆ!',
    profileSubjectProgress: 'ವಿಷಯ ಪ್ರಗತಿ',
    labExperimentNotFound: 'ಪ್ರಯೋಗ ಕಂಡುಬಂದಿಲ್ಲ.',
    labBackTo: 'ಹಿಂದೆ',
    labPrintObservation: 'ಆಬ್ಸರ್ವೇಶನ್ ಮುದ್ರಿಸಿ',
    labNoObservation: 'ಈ ಪ್ರಯೋಗಕ್ಕೆ ಆಬ್ಸರ್ವೇಶನ್ ಟೇಬಲ್ ವ್ಯಾಖ್ಯಾನಿಸಲಿಲ್ಲ.',
    labNoViva: 'ಈ ಪ್ರಯೋಗದ ವಿವಾ ಪ್ರಶ್ನೆಗಳು ಶೀಘ್ರದಲ್ಲೇ ಸೇರುತ್ತವೆ.',
    labNoQuiz: 'ಈ ಪ್ರಯೋಗದ ಕ್ವಿಜ್ ಪ್ರಶ್ನೆಗಳು ಶೀಘ್ರದಲ್ಲೇ ಸೇರುತ್ತವೆ.',
    labQuizCompleted: 'ಕ್ವಿಜ್ ಪೂರ್ಣಗೊಂಡಿದೆ!',
    labSubmitQuiz: 'ಕ್ವಿಜ್ ಸಲ್ಲಿಸಿ',
    labRetakeQuiz: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    labPrevious: 'ಹಿಂದಿನದು',
    labFinish: 'ಮುಗಿಸಿ',
    aboutOpenSource: 'ಓಪನ್ ಸೋರ್ಸ್ ವಿಜ್ಞಾನ ಪ್ರಯೋಗಾಲಯ',
    aboutMissionTitle: 'ನಮ್ಮ ಮಿಷನ್',
    aboutMissionP1: 'ಇ-ಪ್ರಯೋಗ ಕರ್ನಾಟಕ PUC ವಿದ್ಯಾರ್ಥಿಗಳಿಗೆ ಪ್ರಾಯೋಗಿಕ ವಿಜ್ಞಾನ ಶಿಕ್ಷಣವನ್ನು ಪ್ರಜಾಸತ್ತಾತ್ಮಕಗೊಳಿಸಲು ಗುರಿ ಹೊಂದಿದೆ. ಶಾಲೆಯಲ್ಲಿ ಭೌತಿಕ ಲ್ಯಾಬ್ ಇರಲಿ ಅಥವಾ ಇಲ್ಲದಿರಲಿ, ಪ್ರತಿ ವಿದ್ಯಾರ್ಥಿಗೂ ಪ್ರಾಯೋಗಿಕ ಕಲಿಕೆ ದೊರಕಬೇಕು ಎಂದು ನಾವು ನಂಬುತ್ತೇವೆ.',
    aboutMissionP2: 'ನಮ್ಮ 2D ಸಂವಾದಾತ್ಮಕ ಸಿಮ್ಯುಲೇಷನ್‌ಗಳು ಆಬ್ಸರ್ವೇಶನ್, ವಿವಾ ವೋಸ್, ಕ್ವಿಜ್ ಮತ್ತು AI ಸಂದೇಹ ನಿವಾರಣೆ ಸಹಿತ ನಿಜ ಪ್ರಯೋಗಗಳನ್ನು ಪ್ರತಿಬಿಂಬಿಸುತ್ತವೆ. ಎಲ್ಲವೂ ಬ್ರೌಸರ್‌ನಲ್ಲಿ ಉಚಿತ ಮತ್ತು ಶಾಶ್ವತ.',
    aboutFeat1Title: '2D ಸಂವಾದಾತ್ಮಕ ಸಿಮ್ಯುಲೇಷನ್', aboutFeat1Desc: 'ಎಲ್ಲ ಪ್ರಯೋಗಗಳು ಬ್ರೌಸರ್‌ನಲ್ಲಿ — WebGL ಅಥವಾ ಡೌನ್‌ಲೋಡ್ ಅಗತ್ಯವಿಲ್ಲ.',
    aboutFeat2Title: 'AI ವಿಜ್ಞಾನ ಶಿಕ್ಷಕ', aboutFeat2Desc: 'ಕನ್ನಡ, ಹಿಂದಿ ಅಥವಾ ಇಂಗ್ಲಿಷ್‌ನಲ್ಲಿ ಸಂದೇಹ ಕೇಳಿ — Gemini ಚಾಲಿತ.',
    aboutFeat3Title: 'ಕರ್ನಾಟಕ PUC ಹೊಂದಿಕೆ', aboutFeat3Desc: '1ನೇ ಮತ್ತು 2ನೇ PUC ಎಲ್ಲ 5 ವಿಷಯಗಳ ಪಠ್ಯಕ್ರಮ ಒಳಗೊಂಡಿದೆ.',
    aboutFeat4Title: 'ಸುರಕ್ಷಿತ ಮತ್ತು ಸುಲಭ', aboutFeat4Desc: 'ರಾಸಾಯನಿಕ ಇಲ್ಲ, ಅಪಾಯ ಇಲ್ಲ — ಎಲ್ಲಿ ಬೇಕಾದರೂ ಪ್ರಯೋಗ ಮಾಡಿ.',
    aboutFeat5Title: 'ಬಹುಭಾಷಾ ಬೆಂಬಲ', aboutFeat5Desc: 'ಇಂಗ್ಲಿಷ್, ಕನ್ನಡ ಮತ್ತು ಹಿಂದಿ ಸಂಪೂರ್ಣ ಬೆಂಬಲ.',
    aboutFeat6Title: 'ಗೇಮಿಫೈಡ್ ಕಲಿಕೆ', aboutFeat6Desc: 'ಕ್ವಿಜ್, ವಿವಾ ವೋಸ್, ಅಸೈನ್‌ಮೆಂಟ್ ಮತ್ತು ಪ್ರಗತಿ ಟ್ರ್ಯಾಕಿಂಗ್.',
    aboutFeaturesSubheading: 'ಭಾರತೀಯ ತರಗತಿಗಾಗಿ ರಚಿಸಲಾದ ಪ್ರಾಯೋಗಿಕ ವಿಜ್ಞಾನ ಶಿಕ್ಷಣದ ಎಲ್ಲ ಅಗತ್ಯಗಳು.',
    aboutSubjectsHeading: 'ಒಳಗೊಂಡ ವಿಷಯಗಳು', aboutSubjectsSubheading: '5 PUC ವಿಜ್ಞಾನ ವಿಭಾಗಗಳ ಸಮಗ್ರ ವ್ಯಾಪ್ತಿ.',
    aboutBuiltWith: 'ನಿರ್ಮಿಸಲಾಗಿದೆ', aboutBuiltFor: 'ಕರ್ನಾಟಕ ವಿದ್ಯಾರ್ಥಿಗಳಿಗಾಗಿ',
    aboutCtaSubheading: 'ಸಂವಾದಾತ್ಮಕ ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ಕಲಿಯುತ್ತಿರುವ ಸಾವಿರಾರು ಕರ್ನಾಟಕ ವಿದ್ಯಾರ್ಥಿಗಳೊಂದಿಗೆ ಸೇರಿ.',
    profileEmailLabel: 'ಇಮೇಲ್', profileIdLabel: 'ID', profileJoinedLabel: 'ಸೇರಿದ ದಿನಾಂಕ',
    profileDisplayName: 'ಹೆಸರು', profileInstitution: 'ಸಂಸ್ಥೆ',
    profileGradeClass: 'ತರಗತಿ', profileBoardSyllabus: 'ಬೋರ್ಡ್ / ಪಠ್ಯಕ್ರಮ',
    profileLanguageLabel: 'ಭಾಷೆ', profileThemeColor: 'ಥೀಮ್ ಬಣ್ಣ',
    profileNotSet: 'ಹೊಂದಿಸಿಲ್ಲ',
    tabAim: 'ಉದ್ದೇಶ & ಸಿದ್ಧಾಂತ', tabProcedure: 'ವಿಧಾನ', tabInstructions: 'ಸೂಚನೆಗಳು & ವೀಡಿಯೊ', tabSimulation: 'ಸಿಮ್ಯುಲೇಷನ್',
    tabObservation: 'ಅವಲೋಕನ', tabResult: 'ಫಲಿತಾಂಶ', tabRealWorld: 'ನಿಜ ಜಗತ್ತು', tabViva: 'ವಿವಾ ಪ್ರಶ್ನೆಗಳು', tabQuiz: 'ಕ್ವಿಜ್',
    labAimHeading: 'ಉದ್ದೇಶ', labRequirements: 'ಅಗತ್ಯಗಳು', labTheory: 'ಸಿದ್ಧಾಂತ', labObjectives: 'ಗುರಿಗಳು',
    labSafetyPrecautions: 'ಸುರಕ್ಷತಾ ಮುನ್ನೆಚ್ಚರಿಕೆಗಳು', labProcedureHeading: 'ವಿಧಾನ', labInstructionsHeading: 'ಲ್ಯಾಬ್ ಸೂಚನೆಗಳು',
    labVideoDemo: 'ವೀಡಿಯೊ ಪ್ರದರ್ಶನ', labVideoComingSoon: 'ವೀಡಿಯೊ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ', labSearchYouTube: 'YouTube ನಲ್ಲಿ ಹುಡುಕಿ',
    labObservationTable: 'ಅವಲೋಕನ ಕೋಷ್ಟಕ', labResultConclusion: 'ಫಲಿತಾಂಶ & ತೀರ್ಮಾನ', labExpectedResultFormat: 'ನಿರೀಕ್ಷಿತ ಫಲಿತಾಂಶ ಸ್ವರೂಪ:',
    labYourResult: 'ನಿಮ್ಮ ಫಲಿತಾಂಶ', labWriteResult: 'ನಿಮ್ಮ ಫಲಿತಾಂಶ ಮತ್ತು ತೀರ್ಮಾನ ಬರೆಯಿರಿ...', labExperimentalValue: 'ಪ್ರಾಯೋಗಿಕ ಮೌಲ್ಯ', labPercentageError: 'ಶೇಕಡಾ ದೋಷ',
    labRealWorldApps: 'ನಿಜ ಜಗತ್ತಿನ ಅನ್ವಯಗಳು', labRealWorldDefault: 'ಈ ಪ್ರಯೋಗದ ನಿಜ ಜಗತ್ತಿನ ಅನ್ವಯಗಳು:',
    labInteractiveViva: 'ಸಂವಾದಾತ್ಮಕ ವಿವಾ ವೋಸ್', labRevealed: 'ಬಹಿರಂಗಗೊಂಡಿದೆ', labShuffleQuestions: 'ಪ್ರಶ್ನೆಗಳನ್ನು ಮರುಜೋಡಿಸಿ',
    labRevealAnswer: 'ಉತ್ತರ ತೋರಿಸಿ', labHowDidYouDo: 'ನೀವು ಹೇಗೆ ಮಾಡಿದಿರಿ?', labKnew: 'ತಿಳಿದಿತ್ತು', labUnsure: 'ಖಚಿತವಿಲ್ಲ', labMissed: 'ತಪ್ಪಿತು',
    labPracticeSummary: 'ಅಭ್ಯಾಸ ಸಾರಾಂಶ', labSelfAssessmentQuiz: 'ಸ್ವ-ಮೌಲ್ಯಮಾಪನ ಕ್ವಿಜ್', labAnswered: 'ಉತ್ತರಿಸಲಾಗಿದೆ', labExplanation: 'ವಿವರಣೆ:',
    toolFormulaTitle: 'ಸೂತ್ರ ಹಾಳೆ', toolFormulaSubtitle: 'ಶೀಘ್ರ ಉಲ್ಲೇಖಕ್ಕಾಗಿ ಪ್ರಮಾಣಿತ ಸೂತ್ರಗಳು ಮತ್ತು ಸಮೀಕರಣಗಳು.',
    toolFormulaSearchPlaceholder: 'ಸೂತ್ರ ಹುಡುಕಿ...', toolFormulaNoResults: 'ನಿಮ್ಮ ಹುಡುಕಾಟಕ್ಕೆ ಯಾವುದೇ ಸೂತ್ರ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ.',
    toolSafetyTitle: 'ಪ್ರಯೋಗಾಲಯ ಸುರಕ್ಷತಾ ಮಾರ್ಗದರ್ಶಿ', toolSafetySubtitle: 'ಎಲ್ಲ ಪ್ರಯೋಗಗಳಿಗೆ ಅಗತ್ಯ ಸುರಕ್ಷತಾ ಪ್ರೋಟೋಕಾಲ್ ಮತ್ತು ತುರ್ತು ಕಾರ್ಯವಿಧಾನಗಳು.',
    toolSafetySearchPlaceholder: 'ಮಾರ್ಗದರ್ಶನ ಹುಡುಕಿ...', toolSafetyNoResults: 'ಯಾವುದೇ ಸುರಕ್ಷತಾ ನಿಯಮ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ.',
    toolConstantsTitle: 'ಭೌತಿಕ ಸ್ಥಿರಾಂಕಗಳು', toolConstantsSubtitle: 'ಸಾರ್ವತ್ರಿಕ ಮತ್ತು ಮೂಲಭೂತ ಭೌತಿಕ ಸ್ಥಿರಾಂಕಗಳ ಆರ್ಥಿಕ ಮೌಲ್ಯಗಳು.',
    toolConstantsSearchPlaceholder: 'ಸ್ಥಿರಾಂಕ ಹುಡುಕಿ...', toolConstantsNoResults: 'ಯಾವುದೇ ಸ್ಥಿರಾಂಕ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ.',
    toolCalculatorTitle: 'ಕ್ಯಾಲ್ಕುಲೇಟರ್', toolCalcStandard: 'ಸಾಮಾನ್ಯ', toolCalcScientific: 'ವೈಜ್ಞಾನಿಕ',
    toolBioDiagramsTitle: 'ಜೀವಶಾಸ್ತ್ರ ರೇಖಾಚಿತ್ರಗಳು', toolBioDiagramsSubtitle: 'ಜೀವಶಾಸ್ತ್ರಕ್ಕಾಗಿ ಸಂವಾದಾತ್ಮಕ ಲೇಬಲ್ ರೇಖಾಚಿತ್ರಗಳು.',
    toolLogicGatesTitle: 'ಲಾಜಿಕ್ ಗೇಟ್ಸ್ ಸಿಮ್ಯುಲೇಟರ್', toolLogicGatesSubtitle: 'ಸಂವಾದಾತ್ಮಕ ಗೇಟ್ ಸಿಮ್ಯುಲೇಷನ್‌ಗಳ ಮೂಲಕ ಬೂಲಿಯನ್ ತರ್ಕ ಅನ್ವೇಷಿಸಿ.',
    toolPeriodicTableTitle: 'ಆವರ್ತ ಕೋಷ್ಟಕ', toolPeriodicTableSubtitle: 'ಅಂಶಗಳ ಸಂವಾದಾತ್ಮಕ ಆವರ್ತ ಕೋಷ್ಟಕ.',
    toolSearchAll: 'ಎಲ್ಲ', toolCopied: 'ನಕಲಿಸಲಾಗಿದೆ!',
  },

  hi: {
    navHome: 'होम', navTools: 'टूल्स', navAbout: 'बारे में',
    navExperiments: 'प्रयोग', navTutor: 'AI शिक्षक', navDashboard: 'डैशबोर्ड',
    navLogin: 'लॉग इन', navLogout: 'लॉग आउट', navProfile: 'प्रोफ़ाइल',
    heroBadge: 'कर्नाटक PUC वर्चुअल साइंस लैब',
    heroDesc: 'कर्नाटक PUC छात्रों के लिए 42 इंटरेक्टिव वर्चुअल विज्ञान प्रयोग। AI, Canvas & SVG द्वारा संचालित — डिजिटल तरीके से सीखें।',
    heroCta: 'लैब देखें →', heroCtaAi: 'AI शिक्षक',
    statsExperiments: 'प्रयोग', statsSubjects: 'विषय', statsLabs: 'कर्नाटक PUC लैब्स', statsAi: 'AI संचालित',
    subjectsHeading: '5 विषय, 42 लैब्स',
    subjectsSubheading: 'कर्नाटक प्री-यूनिवर्सिटी पाठ्यक्रम के अनुसार हर प्रयोग।',
    labsLabel: 'लैब्स',
    featuresHeading: 'E-Prayog क्यों?',
    feat1Title: 'इंटरेक्टिव 2D सिमुलेशन', feat1Desc: 'हर प्रयोग के लिए Canvas & SVG लैब्स।',
    feat2Title: 'AI लैब शिक्षक', feat2Desc: 'आपके वर्तमान प्रयोग को जानने वाला Gemini AI।',
    feat3Title: 'कर्नाटक PUC पाठ्यक्रम', feat3Desc: '1st और 2nd PUC पाठ्यक्रम के अनुसार हर लैब।',
    feat4Title: 'रियल-टाइम गणना', feat4Desc: 'त्रुटि विश्लेषण और ग्राफिंग के साथ लाइव इंजन।',
    feat5Title: 'मोबाइल फ्रेंडली', feat5Desc: 'किसी भी डिवाइस पर सीखें — फोन, टैबलेट या लैपटॉप।',
    feat6Title: 'वाइवा प्रश्न', feat6Desc: 'चुने हुए Q&A से प्रैक्टिकल परीक्षा की तैयारी करें।',
    ctaHeading: 'प्रयोग के लिए तैयार?', ctaSubheading: 'वर्चुअल लैब यात्रा शुरू करें — कोई रसायन नहीं, कोई उपकरण नहीं, बस सीखना।', ctaBtn: 'सीखना शुरू करें →',
    tutorTitle: 'AI लैब शिक्षक', tutorSubtitle: 'Gemini AI द्वारा संचालित • कर्नाटक PUC पाठ्यक्रम',
    tutorPlaceholder: 'कर्नाटक PUC विज्ञान के बारे में कुछ भी पूछें...', tutorSend: 'भेजें', tutorClear: 'चैट साफ करें',
    tutorWelcome: 'नमस्कार। मैं आपका E-Prayog AI शिक्षक हूँ। कर्नाटक PUC विज्ञान प्रैक्टिकल के बारे में — भौतिकी, रसायन, जीव विज्ञान, गणित या कंप्यूटर विज्ञान — कुछ भी पूछें।',
    tutorDisclaimer: 'Gemini AI द्वारा संचालित — महत्वपूर्ण जानकारी हमेशा सत्यापित करें',
    tutorQ1: "ओम का नियम क्या है?", tutorQ2: 'प्रकाश संश्लेषण समझाएं', tutorQ3: 'दर्पण सूत्र क्या है?',
    tutorQ4: 'माइटोसिस और मेयोसिस में अंतर', tutorQ5: 'व्हीटस्टोन ब्रिज का सिद्धांत', tutorQ6: 'अम्ल-क्षार अनुमापन समझाएं',
    aiGreeting: "नमस्कार। मैं आपका E-Prayog AI शिक्षक हूँ। किसी भी कर्नाटक PUC प्रयोग के बारे में पूछें।",
    aiGreetingLab: "नमस्कार। आप **{lab}** ({subject}) पर काम कर रहे हैं। इस प्रयोग के बारे में कुछ भी पूछें।",
    aiGeneral: 'Gemini AI • सामान्य मोड',
    aiAskPlaceholder: 'किसी भी प्रयोग के बारे में पूछें…', aiAskLabPlaceholder: '{lab} के बारे में पूछें…',
    aiDisclaimer: 'Gemini AI द्वारा संचालित — जानकारी सत्यापित करें',
    aiError: 'कनेक्शन समस्या। कृपया पुनः प्रयास करें।', aiRateLimit: 'दर सीमा पार हो गई। कृपया एक मिनट प्रतीक्षा करें।',
    aboutTitle: 'कर्नाटक में विज्ञान शिक्षा को नया रूप',
    aboutDesc: 'E-Prayog इंटरैक्टिव 2D सिमुलेशन, AI ट्यूटर और कर्नाटक छात्रों के लिए विशेष पाठ्यक्रम के साथ हर PUC प्रयोग को जीवंत बनाता है।',
    aboutExploreLabs: 'लैब देखें',
    aboutTryTutor: 'AI ट्यूटर आज़माएं',
    toolsTitle: 'वैज्ञानिक टूल्स',
    toolsDesc: 'आपके सभी विज्ञान प्रयोगों के लिए संदर्भ, कैलकुलेटर और इंटरैक्टिव अध्ययन सहायक का त्वरित उपयोग।',
    toolsFormulaSheet: 'सूत्र पत्रक',
    toolsLogicGates: 'लॉजिक गेट्स',
    toolsPeriodicTable: 'आवर्त सारणी',
    toolsConstants: 'स्थिरांक',
    toolsCalculator: 'कैलकुलेटर',
    toolsSafetyGuide: 'सुरक्षा गाइड',
    toolsBioDiagrams: 'बायो डायग्राम',
    subjectsTitle: 'वर्चुअल प्रयोगशालाएं',
    subjectsDesc: 'कर्नाटक PUC पाठ्यक्रम के अनुरूप इंटरैक्टिव प्रयोग देखने के लिए विषय चुनें।',
    subjectsExperiments: 'प्रयोग',
    subjectsMore: 'और',
    subjectsExplore: 'देखें',
    subjectBack: 'विषयों पर वापस जाएं',
    subjectNotFound: 'विषय नहीं मिला।',
    subjectKarnatakaPuc: 'कर्नाटक PUC',
    subjectDifficulty: 'कठिनाई',
    subjectStandard: 'कक्षा',
    subjectAll: 'सभी',
    subjectOpenLab: 'लैब खोलें',
    subjectNoExperiments: 'चयनित फ़िल्टर से कोई प्रयोग नहीं मिला।',
    diffEasy: 'आसान', diffMedium: 'मध्यम', diffHard: 'कठिन',
    std1stPuc: '1st PUC', std2ndPuc: '2nd PUC',
    namePhysics: 'भौतिकी', nameChemistry: 'रसायन', nameBiology: 'जीव विज्ञान', nameMath: 'गणित', nameCS: 'CS',
    descPhysics: 'कर्नाटक PUC पाठ्यक्रम के अनुसार इंटरैक्टिव 2D सिमुलेशन के माध्यम से यांत्रिकी, प्रकाशिकी, विद्युत और चुंबकत्व का अन्वेषण करें।',
    descChemistry: 'कर्नाटक PUC के लिए 2D सिमुलेशन के माध्यम से अनुमापन, नमक विश्लेषण, क्रोमैटोग्राफी और अभिक्रिया गतिकी करें।',
    descBiology: 'कर्नाटक PUC के लिए कोशिका जीव विज्ञान, आनुवंशिकी, पादप क्रियाविज्ञान और जैव रसायन को 2D सिमुलेशन से अन्वेषित करें।',
    descMath: 'कर्नाटक PUC के लिए त्रिकोणमिति, बीजगणित, सांख्यिकी और प्रायिकता को इंटरैक्टिव 2D अन्वेषण से समझें।',
    descCS: 'कर्नाटक PUC के लिए सॉर्टिंग एल्गोरिदम, डेटा संरचनाएं और लॉजिक गेट्स को एनिमेटेड 2D सिमुलेशन से देखें।',
    contactTitle: 'हमें प्रतिक्रिया भेजें',
    contactDesc: 'E-Prayog को बेहतर बनाने में मदद करें। आपकी प्रतिक्रिया महत्वपूर्ण है!',
    contactThankYou: 'धन्यवाद!',
    contactSubmitted: 'आपकी प्रतिक्रिया सफलतापूर्वक भेज दी गई है।',
    contactSubmitAnother: 'एक और भेजें',
    contactRatingPrompt: 'आप E-Prayog को कितनी रेटिंग देंगे?',
    contactCategory: 'श्रेणी',
    contactMessage: 'आपका संदेश',
    contactPlaceholder: 'अपना विचार बताएं... (कम से कम 20 अक्षर)',
    contactSubmit: 'प्रतिक्रिया भेजें',
    contactRatingRequired: 'कृपया एक रेटिंग चुनें।',
    contactMessageMin: 'संदेश कम से कम 20 अक्षरों का होना चाहिए।',
    contactFailed: 'सबमिट नहीं हुआ। कृपया पुनः प्रयास करें।',
    footerDesc: 'कर्नाटक PUC छात्रों को immersive वर्चुअल विज्ञान सिमुलेशन और AI-आधारित मार्गदर्शन से सशक्त बना रहे हैं। करके सीखें — डिजिटल रूप से।',
    footerPlatform: 'प्लेटफ़ॉर्म',
    footerVirtualLabs: 'वर्चुअल लैब्स',
    footerSupport: 'सहायता',
    footerContactUs: 'संपर्क करें',
    footerAboutUs: 'हमारे बारे में',
    footerPrivacy: 'गोपनीयता नीति',
    footerTerms: 'नियम और शर्तें',
    footerFeedback: 'प्रतिक्रिया',
    footerFeedbackDesc: 'आपके सीखने के अनुभव को बेहतर बनाने में मदद करें।',
    footerFeedbackPlaceholder: 'आपके सुझाव...',
    footerFeedbackThanks: 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
    footerRights: 'सभी अधिकार सुरक्षित।',
    footerBuiltFor: 'के लिए बनाया गया',
    footerKarnatakaStudents: 'कर्नाटक PUC छात्र',
    loginWelcome: 'फिर से स्वागत है',
    loginCreateAccount: 'खाता बनाएं',
    loginCompleteProfile: 'अपनी प्रोफ़ाइल पूरी करें',
    loginJoinToday: 'आज ही E-Prayog से जुड़ें',
    loginFewDetails: 'बस कुछ और विवरण',
    loginToAccount: 'अपने E-Prayog खाते में लॉग इन करें',
    loginTeacherBadge: 'शिक्षक लॉगिन',
    loginAdminBadge: 'एडमिन लॉगिन',
    loginBack: 'वापस',
    loginFullName: 'पूरा नाम',
    loginPassword: 'पासवर्ड',
    loginNext: 'आगे',
    loginOr: 'या',
    loginContinueGoogle: 'Google से जारी रखें',
    loginHaveAccount: 'क्या आपका पहले से खाता है?',
    loginNoAccount: 'क्या आपका खाता नहीं है?',
    loginSignUp: 'साइन अप',
    loginTeacherHint: 'शिक्षक खाते एडमिन द्वारा बनाए जाते हैं।',
    loginAdminHint: 'एडमिन क्रेडेंशियल प्लेटफ़ॉर्म सेटअप के दौरान सेट होते हैं।',
    profileTitle: 'आपकी प्रोफ़ाइल',
    profileSaved: 'प्रोफ़ाइल सहेजी गई!',
    profileEdit: 'प्रोफ़ाइल संपादित करें',
    profileAccountSettings: 'खाता सेटिंग्स',
    profileCancel: 'रद्द करें',
    profileSave: 'सहेजें',
    profileStats: 'आपके आँकड़े',
    profileCurrentStreak: 'वर्तमान स्ट्रीक',
    profileLabsCompleted: 'पूर्ण लैब्स',
    profileOverallProgress: 'कुल प्रगति',
    profileYourTeacher: 'आपके शिक्षक',
    profileJoinClassHelp: 'अपने शिक्षक का 6-अक्षर क्लास कोड दर्ज करें।',
    profileLeave: 'छोड़ें',
    profileLinked: 'लिंक हो गया!',
    profileSubjectProgress: 'विषय प्रगति',
    labExperimentNotFound: 'प्रयोग नहीं मिला।',
    labBackTo: 'वापस',
    labPrintObservation: 'ऑब्ज़र्वेशन प्रिंट करें',
    labNoObservation: 'इस प्रयोग के लिए ऑब्ज़र्वेशन टेबल उपलब्ध नहीं है।',
    labNoViva: 'इस प्रयोग के viva प्रश्न जल्द जोड़े जाएंगे।',
    labNoQuiz: 'इस प्रयोग के quiz प्रश्न जल्द जोड़े जाएंगे।',
    labQuizCompleted: 'क्विज़ पूरा हुआ!',
    labSubmitQuiz: 'क्विज़ सबमिट करें',
    labRetakeQuiz: 'क्विज़ फिर दें',
    labPrevious: 'पिछला',
    labFinish: 'समाप्त',
    aboutOpenSource: 'ओपन सोर्स साइंस लैब',
    aboutMissionTitle: 'हमारा मिशन',
    aboutMissionP1: 'E-Prayog का लक्ष्य कर्नाटक PUC छात्रों के लिए प्रायोगिक विज्ञान शिक्षा को सुलभ बनाना है। हम मानते हैं कि हर छात्र — चाहे उनके स्कूल में लैब हो या न हो — को hands-on प्रयोगात्मक शिक्षा मिलनी चाहिए।',
    aboutMissionP2: 'हमारे 2D इंटरेक्टिव सिमुलेशन ऑब्ज़र्वेशन, वाइवा वोसे, क्विज़ और AI-आधारित समाधान सहित वास्तविक प्रयोगों को दोबारा प्रस्तुत करते हैं। सब कुछ ब्राउज़र में — मुफ़्त, हमेशा के लिए।',
    aboutFeat1Title: '2D इंटरेक्टिव सिमुलेशन', aboutFeat1Desc: 'सभी प्रयोग ब्राउज़र में चलते हैं — कोई WebGL नहीं, कोई डाउनलोड नहीं।',
    aboutFeat2Title: 'AI विज्ञान शिक्षक', aboutFeat2Desc: 'अंग्रेजी, कन्नड़ या हिंदी में संदेह पूछें — Gemini द्वारा संचालित।',
    aboutFeat3Title: 'कर्नाटक PUC अनुरूप', aboutFeat3Desc: '1st और 2nd PUC के सभी 5 विज्ञान विषयों का पाठ्यक्रम शामिल है।',
    aboutFeat4Title: 'सुरक्षित और सुलभ', aboutFeat4Desc: 'कोई रसायन नहीं, कोई जोखिम नहीं — कहीं भी, कभी भी प्रयोग करें।',
    aboutFeat5Title: 'बहुभाषी समर्थन', aboutFeat5Desc: 'पूर्ण अंग्रेजी, कन्नड़ और हिंदी समर्थन।',
    aboutFeat6Title: 'गेमिफाइड लर्निंग', aboutFeat6Desc: 'क्विज़, वाइवा वोसे, असाइनमेंट और प्रगति ट्रैकिंग।',
    aboutFeaturesSubheading: 'भारतीय कक्षा के लिए बनाई गई प्रायोगिक विज्ञान शिक्षा की सभी आवश्यकताएं।',
    aboutSubjectsHeading: 'कवर किए गए विषय', aboutSubjectsSubheading: '5 PUC विज्ञान धाराओं का व्यापक कवरेज।',
    aboutBuiltWith: 'बनाया गया', aboutBuiltFor: 'कर्नाटक छात्रों के लिए',
    aboutCtaSubheading: 'इंटरेक्टिव सिमुलेशन के माध्यम से सीख रहे हजारों कर्नाटक छात्रों के साथ जुड़ें।',
    profileEmailLabel: 'ईमेल', profileIdLabel: 'ID', profileJoinedLabel: 'शामिल हुए',
    profileDisplayName: 'नाम', profileInstitution: 'संस्थान',
    profileGradeClass: 'कक्षा', profileBoardSyllabus: 'बोर्ड / पाठ्यक्रम',
    profileLanguageLabel: 'भाषा', profileThemeColor: 'थीम रंग',
    profileNotSet: 'सेट नहीं',
    tabAim: 'उद्देश्य & सिद्धांत', tabProcedure: 'प्रक्रिया', tabInstructions: 'निर्देश & वीडियो', tabSimulation: 'सिमुलेशन',
    tabObservation: 'अवलोकन', tabResult: 'परिणाम', tabRealWorld: 'वास्तविक दुनिया', tabViva: 'वाइवा प्रश्न', tabQuiz: 'क्विज़',
    labAimHeading: 'उद्देश्य', labRequirements: 'आवश्यकताएं', labTheory: 'सिद्धांत', labObjectives: 'लक्ष्य',
    labSafetyPrecautions: 'सुरक्षा सावधानियां', labProcedureHeading: 'प्रक्रिया', labInstructionsHeading: 'लैब निर्देश',
    labVideoDemo: 'वीडियो प्रदर्शन', labVideoComingSoon: 'वीडियो प्रदर्शन जल्द आ रहा है', labSearchYouTube: 'YouTube पर खोजें',
    labObservationTable: 'अवलोकन तालिका', labResultConclusion: 'परिणाम & निष्कर्ष', labExpectedResultFormat: 'अपेक्षित परिणाम प्रारूप:',
    labYourResult: 'आपका परिणाम', labWriteResult: 'यहाँ अपना परिणाम और निष्कर्ष लिखें...', labExperimentalValue: 'प्रयोगात्मक मान', labPercentageError: 'प्रतिशत त्रुटि',
    labRealWorldApps: 'वास्तविक दुनिया के अनुप्रयोग', labRealWorldDefault: 'इस प्रयोग के वास्तविक दुनिया के अनुप्रयोगों में शामिल हैं:',
    labInteractiveViva: 'इंटरेक्टिव वाइवा वोसे', labRevealed: 'प्रकट', labShuffleQuestions: 'प्रश्न फेरबदल करें',
    labRevealAnswer: 'उत्तर दिखाएं', labHowDidYouDo: 'आपने कैसा किया?', labKnew: 'जानता था', labUnsure: 'अनिश्चित', labMissed: 'चूक गया',
    labPracticeSummary: 'अभ्यास सारांश', labSelfAssessmentQuiz: 'स्व-मूल्यांकन क्विज़', labAnswered: 'उत्तर दिया', labExplanation: 'व्याख्या:',
    toolFormulaTitle: 'सूत्र पत्र', toolFormulaSubtitle: 'त्वरित संदर्भ के लिए मानक सूत्र और समीकरण।',
    toolFormulaSearchPlaceholder: 'सूत्र खोजें...', toolFormulaNoResults: 'कोई सूत्र आपकी खोज से मेल नहीं खाया।',
    toolSafetyTitle: 'प्रयोगशाला सुरक्षा गाइड', toolSafetySubtitle: 'सभी प्रयोगशाला प्रयोगों के लिए आवश्यक सुरक्षा प्रोटोकॉल और आपातकालीन प्रक्रियाएं।',
    toolSafetySearchPlaceholder: 'दिशानिर्देश खोजें...', toolSafetyNoResults: 'कोई सुरक्षा नियम मेल नहीं खाया।',
    toolConstantsTitle: 'भौतिक स्थिरांक', toolConstantsSubtitle: 'सार्वभौमिक और मौलिक भौतिक स्थिरांकों के संदर्भ मान।',
    toolConstantsSearchPlaceholder: 'स्थिरांक खोजें...', toolConstantsNoResults: 'कोई स्थिरांक मेल नहीं खाया।',
    toolCalculatorTitle: 'कैलकुलेटर', toolCalcStandard: 'मानक', toolCalcScientific: 'वैज्ञानिक',
    toolBioDiagramsTitle: 'जीव विज्ञान आरेख', toolBioDiagramsSubtitle: 'जीव विज्ञान के लिए इंटरेक्टिव लेबल आरेख।',
    toolLogicGatesTitle: 'लॉजिक गेट्स सिमुलेटर', toolLogicGatesSubtitle: 'इंटरेक्टिव गेट सिमुलेशन के साथ बूलियन तर्क का अन्वेषण करें।',
    toolPeriodicTableTitle: 'आवर्त सारणी', toolPeriodicTableSubtitle: 'तत्वों की इंटरेक्टिव आवर्त सारणी।',
    toolSearchAll: 'सभी', toolCopied: 'कॉपी किया!',
  },
};

interface LanguageContextValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextValue>({
  lang: 'en', setLang: () => {}, t: T.en,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const stored = (typeof localStorage !== 'undefined' && localStorage.getItem('eprayog-lang')) as Lang | null;
  const [lang, setLangState] = useState<Lang>(stored ?? 'en');
  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem('eprayog-lang', l);
  }, []);
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLang = () => useContext(LanguageContext);
export { T };
