query AllSubjects @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  subjects(orderBy: [{createdAt: DESC}]) {
    id
    name
    description
  }
}

query MyQuestions @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  questions(where: {askerId: {eq_expr: "auth.uid"}}, orderBy: [{createdAt: DESC}]) {
    id
    title
    content
    createdAt
    tags
    subject {
      name
    }
  }
}

mutation CreateLearningResource($title: String!, $type: String!, $content: String, $subjectId: UUID!) @auth(level: USER, insecureReason: "This operation allows logged-in users to create learning resources.") {
  learningResource_insert(data: {
    title: $title,
    type: $type,
    content: $content,
    creatorId_expr: "auth.uid",
    subjectId: $subjectId,
    createdAt_expr: "request.time"
  }) {
    id
  }
}

mutation UpdateUserProfile($displayName: String, $bio: String, $profilePictureUrl: String) @auth(level: USER, insecureReason: "This operation allows logged-in users to update their own profile.") {
  user_update(
    key: {id_expr: "auth.uid"},
    data: {
      displayName: $displayName,
      bio: $bio,
      profilePictureUrl: $profilePictureUrl
    }
  ) {
    id
  }
}